### ISSUE TITLE
Solution alternative or not?

### ISSUE THREAD

**Issue by ujhazib** [fecjanky/poly_vector#2]
Isn't this the same?

https://www.boost.org/doc/libs/1_65_0/doc/html/poly_collection/an_efficient_polymorphic_data_st.html

I mean I would rather give trust to something which made into boost. And if I'm not mistaken this was even earlier.

**Comment by ferenj-gs** [comment]
Hey,

Thanks for the interest. I originally envisioned this container when I was working on a telco project around 2014. I was not aware that boost has something like this and based on the date my idea preceded it. There are definitely some similarities, but in my model there is only a single storage that is partitioned to a control block and the data. And the derived objects are laid out contiguously and IIUC the boost version groups it per derived object. My container also support parametrization in terms of a cloning policy class to easily adapt it to existing polymorphic hierarchies, or use the delegate policy by default to store type related information during insertion.

Thanks & BR,
Ferenc
